site_index:
    pattern: /
    defaults: { _controller: MainSiteBundle:Default:index, _locale: %locale% }
    
site:
    prefix:   /{_locale}
    resource: "@MainSiteBundle/Controller/"
    type:     annotation
    defaults: {_locale: %locale% }
    requirements:
      _locale : \w{2}        
      