site_index:
    pattern: /
    defaults: { _controller: MainSiteBundle:Default:index, _locale: %locale% }
    
site:
    prefix:   /{_locale}
    resource: "@MainSiteBundle/Controller/DefaultController.php"
    type:     annotation
    defaults: {_locale: %locale% }
    requirements:
      _locale : \w{2}        
site_catalog:
    prefix:   /{_locale}/
    resource: "@MainSiteBundle/Controller/CatalogController.php"
    type:     annotation
    defaults: {_locale: %locale% }
    requirements:
      _locale : \w{2} 
site_cart:
    prefix:   /{_locale}/
    resource: "@MainSiteBundle/Controller/CartController.php"
    type:     annotation
    defaults: {_locale: %locale% }
    requirements:
      _locale : \w{2} 
news:
    prefix:   /{_locale}/news/
    resource: "@MainSiteBundle/Controller/NewsController.php"
    type:     annotation
    #defaults: { _controller: MainSiteBundle:News:index, _locale: %locale% }
    requirements:
      _locale : \w{2}        
usercabinet:
    prefix:   /{_locale}/
    resource: "@MainSiteBundle/Controller/UsercabinetController.php"
    type:     annotation
    #defaults: { _controller: MainSiteBundle:News:index, _locale: %locale% }
    requirements:
      _locale : \w{2}   
pdpay:
    prefix:   /{_locale}/pdpay/
    resource: "@MainSiteBundle/Controller/PdpayController.php"
    type:     annotation
    #defaults: { _controller: MainSiteBundle:News:index, _locale: %locale% }
    requirements:
      _locale : \w{2} 