itc_index:
    pattern: /itc/
    defaults: { _controller: ItcAdminBundle:Admin:index, _locale: %locale% }
    
itc_admin_def:
    prefix: /itc/{_locale}
    resource: "@ItcAdminBundle/Controller/"
    type:     annotation
    defaults: {_locale: %locale% }
    requirements:
      _locale : \w{2}
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

_imagine:
    resource: .
    type:     imagine
    
genemu_image:
    resource: "@GenemuFormBundle/Resources/config/routing/image.xml"
    
genemu_upload:
    resource: "@GenemuFormBundle/Resources/config/routing/upload.xml"
    
#hansa_site:
#    resource: "@HansaSiteBundle/Controller/"
#    type:     annotation
#    prefix:   /
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
